end Task
MikiUA/GooseTrack-backend pull request #18
Opened 2023-06-06 18:08 UTC by Dmytro-Avramenko

Всім привіт, запушив свою таску, є ще питання чи могли б сьогодні обговорити. Там по Shemas. Helpers і Middleware точно співпадатимуть то можна їх звести до однієї я в коді в себе поправлю. Також я використав в packege.json старий nanoid 3.3.4.

2023-06-07 06:40 UTC, MikiUA requested changes

2023-06-07 06:40 UTC, MikiUA commented on app.js
Router Убирай свой отсюда, в роутере уже всё есть

2023-06-07 06:40 UTC, MikiUA commented on helpers/ctrlWrapper.js
> +const ctrlWrapper = ctrl => {
Этот хелпер убирай, в helper'ах уже прописан ErrorHandler, и все контроллеры обёрнуты в handled(doSomething), посмотри как в auth роутере

2023-06-07 06:40 UTC, MikiUA commented on helpers/HttpError.js
> +const HttpError = (status, message) => {
Это тоже убирай, уже есть CustomError которій можно использовать с помощью throw new CustomError(status,message)

2023-06-07 06:40 UTC, MikiUA commented on middleware/isValidId.js
> +const {isValidObjectId} = require("mongoose");
Это переделываешь из миддлвары в обычную функцию а потом добавляешь в joi валидацию, а то будет много миддлвар, рут нечитаемый, но это необязательно

2023-06-07 06:40 UTC, MikiUA commented on middleware/validateBodyTasks.js
> +            next(HttpError(400, error.message));
next(new CustomError(400,error.message)

2023-06-07 06:40 UTC, MikiUA commented on models/tasks/task.js
> +const { Schema, model } = require("mongoose");
Схему для mongoose перебрасываешь в отдельный файл в папке validSchemas, для файла joi создаешь отдельную папку validationSchemas, в папках моделей оставляешь только второй файл tasks.js

2023-06-07 06:40 UTC, MikiUA commented on helpers/handleMongooseError.js
> +    next()
next(new CustomError(400, 'mongoose validation Error'), чтобы оно сразу передавало в error handler

2023-06-07 06:40 UTC, MikiUA commented on package.json
> +    "nanoid": "^3.3.4",
Package.json не трогаешь вообще никогда, если тебе что-то надо в package пишешь тимлиду, а то возникают конфликты.

2023-06-07 06:40 UTC, MikiUA commented on models/tasks/task.js
> +const taskSchema = new Schema({
Надо добавить юзера в схему, каждая таска создаётся кем-то, это можеть быть простой айдишник но лучше реф на юзеров

2023-06-07 06:40 UTC, MikiUA commented on controllers/tasks/tasks.js
> +
Надо добавить фильтр, чтобы оно находило только таски просящего юзера, {user:req.user}, и уже есть миддлвара которая добавляет userID в поле req.user

2023-06-07 06:40 UTC, MikiUA commented on routes/tasksRouter/index.js
> +router.get("/", ctrl.getAllTasks);
добавляешь миддлвару authentificateUser во всех рутах, она добавляет айдишник в req.user

2023-06-07 06:45 UTC, MikiUA commented on models/tasks/tasks.js
> +const fs = require("fs/promises");
вот это вот что вообще за фсы, мы с бд работаем а не с локальной сторой, удаляй если не используешь или апдейть для бд

2023-06-08 22:35 UTC, Dmytro-Avramenko commented on app.js
+

2023-06-08 22:39 UTC, Dmytro-Avramenko commented on helpers/ctrlWrapper.js
> +const ctrlWrapper = ctrl => {
подивися нічого не зрозумів, взяв за онову домашку як там зроблено

2023-06-08 22:43 UTC, Dmytro-Avramenko commented on helpers/HttpError.js
> +const HttpError = (status, message) => {
прибрав замінив де є HttpError на customError

2023-06-08 22:43 UTC, Dmytro-Avramenko commented on middleware/isValidId.js
> +const {isValidObjectId} = require("mongoose");
якщо можна пізніше зроблю, коли вже все запрацює і зможу нормально в себе тестити

2023-06-08 22:48 UTC, Dmytro-Avramenko commented on middleware/validateBodyTasks.js
> +            next(HttpError(400, error.message));
виправив

2023-06-08 22:49 UTC, Dmytro-Avramenko commented on models/tasks/task.js
> +const { Schema, model } = require("mongoose");
теж саме зроблю як зможу нормально тестити в себе на локальному комп'ютер. Але точно зроблю як все запрацює

2023-06-08 22:50 UTC, Dmytro-Avramenko commented on helpers/handleMongooseError.js
> +    next()
виправив

2023-06-08 22:51 UTC, Dmytro-Avramenko commented on package.json
> +    "nanoid": "^3.3.4",
виправив

2023-06-08 22:51 UTC, Dmytro-Avramenko commented on models/tasks/task.js
> +const taskSchema = new Schema({
добавив

2023-06-08 22:55 UTC, Dmytro-Avramenko commented on controllers/tasks/tasks.js
> +
добавив, з міделварою не поняв

2023-06-08 22:58 UTC, Dmytro-Avramenko commented on routes/tasksRouter/index.js
> +router.get("/", ctrl.getAllTasks);
міделвару authentificateUser добавив.

2023-06-08 22:59 UTC, Dmytro-Avramenko commented on models/tasks/tasks.js
> +const fs = require("fs/promises");
вибачаюсь з домашки скопіпастив

2023-06-08 23:06 UTC, Dmytro-Avramenko commented
Поправив

2023-06-09 14:21 UTC, merged